cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"

brew "awscli"
brew "azure-cli"
brew "cloudfoundry/tap/cf-cli"
brew "fish"
brew "git"
brew "heroku"
brew "jq"
brew "neovim"
brew "node"
brew "tmux"
brew "watchman"
brew "yadm"
brew "yarn"

cask "appcleaner"
cask "atom"
cask "bluemix-cli"
cask "dash"
cask "docker"
cask "firefoxdeveloperedition"
cask "font-hack-nerd-font"
cask "font-sourcecodepro-nerd-font"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2"
cask "karabiner-elements"
cask "now"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "slack"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "vox"
cask "whatsapp"
cask "xld"

cask "java8"
brew "maven"
