cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"

brew "fish"
brew "git"
brew "neovim"
brew "node"
brew "tmux"
brew "yadm"
brew "yarn"

cask "atom"
cask "dash"
cask "docker"
cask "firefoxdeveloperedition"
cask "font-hack-nerd-font"
cask "font-sourcecodepro-nerd-font"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "slack"
cask "visual-studio-code"
cask "vox"
cask "whatsapp"

cask "java8"
brew "maven"
