#!/usr/bin/env bash

if command_exists nvim; then
    mkdir -p "$HOME/.config/nvim"
    link_file "`pwd`/init.vim" "$HOME/.config/nvim/init.vim"
    link_file "`pwd`/init.vim" "$HOME/.vimrc"
else
    cp "`pwd`/init.vim" "$HOME/.vimrc"
    sed -e 's/^"!//' "$HOME/.vimrc"
fi

