#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set keyboard repeat delay and rate
xset r rate 200 20

# Keyboard configuration, US and US International
# Switch using Alt+Space
# Set caps lock as additional escape
setxkbmap -layout us,us -variant ,intl -option grp:alt_space_toggle -option caps:escape

# Start urxvt daemon
urxvtd --quiet --opendisplay --fork

# Start syndaemon, to ignore touchpad input while typing
syndaemon -d -k -i 0.3

# Start MEGASync
# megasync &

# Start tilda terminal
# tilda &

# Start redshift
redshift &

# Export Desktop Environment for xdg
export DE="generic"

# Start window manager
exec i3
# exec awesome
# exec enlightenment_start
# exec jwm

