#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# twm &
# xclock -geometry 50x50-1+1 &
# xterm -geometry 80x50+494+51 &
# xterm -geometry 80x20+494-0 &
# exec xterm -geometry 80x66+0+0 -name login

# Set keyboard repeat delay and rate
xset r rate 200 20

# Swap esc and caps lock
setxkbmap -option "caps:swapescape"

# Start urxvt daemon
urxvtd --quiet --opendisplay --fork

# Start syndaemon, to ignore touchpad input while typing
syndaemon -d -k -i 0.3

# Start MEGASync
# megasync &

# Start tilda terminal
# tilda &

# Start redshift
redshift &

# Export Desktop Environment for xdg
export DE="generic"

# Start window manager
exec enlightenment_start
# exec jwm

