#!/usr/bin/env bash

if type xcode-select >&- && xpath=$( xcode-select --print-path ) && \
    test -d "${xpath}" && test -x "${xpath}" ; then
    echo "Xcode command line tools already installed"
else
    echo "Installing Xcode command line tools..."
    xcode-select --install
fi

if command_exists brew; then
    echo "Homebrew already installed"
else
    echo "Installing Homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# echo "Installing Homebrew packages..."
# brew bundle

