#!/usr/bin/env bash

echo "Updating system software..."
sudo softwareupdate --install --all

echo "Updating Homebrew..."
brew update

echo "Updating Homebrew packages..."
brew upgrade

echo "Updating conda..."
conda update conda

echo "Updating conda packages..."
conda update --all

