#!/usr/bin/env bash

### vim ###
if command_exists nvim; then
    mkdir -p "$HOME/.config/nvim"
    link_file "`pwd`/init.vim" "$HOME/.config/nvim/init.vim"
    link_file "`pwd`/init.vim" "$HOME/.vimrc"
else
    cp "`pwd`/init.vim" "$HOME/.vimrc"
    sed -e 's/^"!//' "$HOME/.vimrc"
fi

### tmux ###
link_file "`pwd`/tmux.conf" "$HOME/.tmux.conf"
if ! [ -d ~/.tmux ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

### latex ###
link_file "`pwd`/latexmkrc" "$HOME/.latexmkrc"

### clang-format ###
link_file "`pwd`/clang-format" "$HOME/.clang-format"
