#!/usr/bin/env bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f ~/.Brewfile ]; then
    echo "Installing programs from Homebrew bundle"
    brew bundle --global
  fi

  if [ -d ~/.iterm2 ]; then
    echo "Setting iTerm2 preferences folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder ~/.iterm2
  fi

  if [ ! -f /usr/local/bin/vim ]; then
    echo "Creating vim -> nvim symbolic link"
    ln -s /usr/local/bin/{nvim,vim}
  fi

fi

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping vim"
  vim +PlugUpdate +PlugClean! +PlugUpdate +qall
fi

if [ ! -d ~/.tmux ]; then
  echo "Bootstrapping tmux"
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ~/.tmux/plugins/tpm/bin/install_plugins
fi

echo "Removing README file"
rm ~/README.md
